/* Inlines the markdown documents and the SVG assets into js/docs-content.js so
   the Docs panel works from a single shared file with no network requests.
   Run: node tools/gen-docs.js   (also run by tools/bundle.js) */
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const S = require("../js/shapes.js");

const DOCS = [
  { id: "readme",   title: "Read me",         blurb: "What this is, how to run it, every source used, and the limits", file: "README.md" },
  { id: "findings", title: "Design findings", blurb: "Issues, decisions and the questions to settle before development", file: "FINDINGS.md" },
  { id: "assets",   title: "Asset spec",      blurb: "Artboard, sizing rule, fill and stroke, Sketch and Zeplin notes", file: "ASSET-SPEC.md" }
];

const docs = DOCS.map(d => ({
  id: d.id, title: d.title, blurb: d.blurb, type: "markdown",
  body: fs.readFileSync(path.join(root, d.file), "utf8")
}));

docs.push({
  id: "svg", title: "Shape SVGs", type: "shapes",
  blurb: "The seven exported assets, with their source ready to copy",
  files: S.order.map(id => ({
    id: id,
    label: S.defs[id].label,
    name: "point-" + id + ".svg",
    source: fs.readFileSync(path.join(root, "assets", "shapes", "point-" + id + ".svg"), "utf8").trim()
  }))
});

fs.writeFileSync(path.join(root, "js", "docs-content.js"),
  "/* GENERATED by tools/gen-docs.js - do not edit. */\n" +
  "window.DocsContent = " + JSON.stringify(docs, null, 1) + ";\n");

const kb = (fs.statSync(path.join(root, "js", "docs-content.js")).size / 1024).toFixed(1);
console.log("js/docs-content.js", kb + " KB,", docs.length, "documents");
